# yaml-language-server: $schema=https://taskfile.dev/schema.json

version: "3"

vars:
  GREETING: Hello, world!

tasks:
  export-model:
    desc: Export a model
    cmds:
      - uv run --with "optimum[onnxruntime]" export.py
    silent: false
  audit-data:
    desc: Audit KB to detect issues & posibles solutions
    cmds:
      - go run cmd/audit/main.go
