// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {runtime} from '../models';

export function Greet(arg1:string):Promise<string>;

export function SendMessage(arg1:string):Promise<runtime.RuntimeResult>;

export function SetRuntime(arg1:runtime.Runtime):Promise<void>;
